---
resource_pools:
- name:     small
  network:  shield
  stemcell: (( grab meta.stemcell ))

  cloud_properties:
    cpu: 1
    disk: 4096
    ram: 2048


compilation:
  network: shield
  reuse_compilation_vms: true
  workers: 4

  cloud_properties:
    cpu:  2
    disk: 8096
    ram:  3840


jobs:
- name: shield
  resource_pool: small
