---
resource_pools:
- name: small
  network: shield
  stemcell: (( grab meta.stemcell ))
  cloud_properties:
    cpu: 1
    ram: 2_048
    disk: 4_096

compilation:
  network: shield
  reuse_compilation_vms: true
  workers: 4
  cloud_properties:
    cpu: 2
    ram: 4_096
    disk: 8_096

jobs:
- name: shield
  resource_pool: small
