compilation:
  cloud_properties: {}
  network: shield
  workers: 2
director_uuid: 2b8bb4b6-1bca-41f2-8c51-0bb3223c0622
disk_pools: []
jobs:
- instances: 1
  name: shield
  networks:
  - name: shield
    static_ips:
    - 10.244.28.2
  persistent_disk: 2048
  resource_pool: shield
  templates:
  - name: postgres
    release: shield
  - name: shield-daemon
    release: shield
  - name: shield-agent
    release: shield
  - name: agent-pgtools
    release: shield
  - name: nginx
    release: shield
  - name: toolbelt
    release: toolbelt
  - name: toolbelt-quick
    release: toolbelt
name: bosh-lite-alpha-shield
networks:
- name: shield
  subnets:
  - gateway: 10.244.28.1
    range: 10.244.28.0/24
    static:
    - 10.244.28.2 - 10.244.28.60
  type: manual
properties:
  databases:
    address: 10.244.28.2
    databases:
    - citext: true
      name: shielddb
      tag: shield
    - citext: true
      name: sessionsdb
      tag: sessions
    db_scheme: postgres
    port: 5524
    roles:
    - name: shieldadmin
      password: REDACTED
      tag: admin
    - name: shieldsessions
      password: REDACTED
      tag: sessions
  shield:
    agent:
      autoprovision: https://10.244.28.2
      daemon_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwep89cUhcbiqbPuf5iCKxWwZDvrTBzSOr1JC3/mQh3E82MJ2YVXHMdHoRxfdUjBqspKu7v4ooiEifr1RiNk0XDLlBNEYLx2xjJinNA33nJIRZMKfdB2VB8T0o0bkqCIasciKDLuJLV4fuJK6m1Srj+sa1z/ZUIHKjK4Vn8lT0bzADqCgCvzJxmP+1YyUql/QpzUxLNMVhOzVUtZJGggvizYheeRxceBwqYbHqJ3yp8oXJYb4PipD0/3gcCkB6O1Gsk4+y24Sl4OiPkn65LCpai0qQPZ42rw2xOC1Ac2bKWUSOoG5JGlJCFzBL4HQ/Rbxlg7xjV1u6ot+CmPiTEhpz
    daemon:
      auth:
        api_keys:
          autoprovision: REDACTED
        basic_password: REDACTED
        basic_user: shield
      database:
        db: shielddb
        host: 10.244.28.2
        password: REDACTED
        port: 5524
        type: postgres
        username: shieldadmin
      domain: 10.244.28.2
      name: REDACTED
      ssh_private_key: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEAsHqfPXFIXG4qmz7n+YgisVsGQ760wc0jq9SQt/5kIdxPNjCd
        mFVxzHR6EcX3VIwarKSru7+KKIhIn69UYjZNFwy5QTRGC8dsYyYpzQN95ySEWTCn
        3QdlQfE9KNG5KgiGrHIigy7iS1eH7iSuptUq4/rGtc/2VCByoyuFZ/JU9G8wA6go
        Ar8ycZj/tWMlKpf0Kc1MSzTFYTs1VLWSRoIL4s2IXnkcXHgcKmGx6id8qfKFyWG+
        D4qQ9P94HApAejtRrJOPstuEpeDoj5J+uSwqWotKkD2eNq8NsTgtQHNmyllEjqBu
        SRpSQhcwS+B0P0W8ZYO8Y1dbuqLfgpj4kxIacwIDAQABAoIBAAKZO6EG+v7JbH0u
        tvG4rHIaGgSDWVwFLkJIdf0PlN/ew5fTrW5hy7Qr/uQmGxc2nOnv3st77YfdQdyA
        E2kCza3KNSwdne5seE8Zb8IiDAeMRRqfGcmqYzZOXA0u0WAqEfmWEKYH2bMsTccW
        6S9xshj7R1PEBSeF9soqSOOX8OJMfoyau6tWbL1PZSwJXPHdzcK90hbgSyAkcMRV
        wQeTVNtJW9zA0Ha6U4styrJRc0POOup0QqJTg38EBikTUZw8xJT8mZXWZbQTnU/l
        Y5sPLL370YrMuaVAn1d7dHCTwOlV105DeOFKIRvkQdWwlQMBSCkIDvfeNLdhS1GV
        AqIq9LECgYEA5PwdeCGjYak1v7Lx65bJlyv7sDKPqoLbQrqdpGW9AgBnppLBD0PX
        5ufK4M3VPY06D+KQpRAb+mohBbGcuL0eRan4HiPd0QVwqiv2phtxMBQ2iCvTWHvB
        mI7dlNS3cP/W+r9L9n37mPvfnKBeD0weRC+KvO1PLYz1y75LFigAG+sCgYEAxUy0
        y3NBdy/QJ30glU4aVWs6LUmfAMFO/lWDAfPGQBqUzEcpiRsRrZDCW0uAyDJXtJe3
        E4lXSkPmW9cRS18aLTxkHNENNcGDxYyKvByYRypT0vDx+uz+zwm8gZkL8lGayi4Y
        ebawyj84+dGZjaXg3CPgD6m3YPUq5vdqvkrQgZkCgYEArV07qoI9Qmlr6jE++9Dz
        22JPcf01zDC6dHD5fUgRq3xG/VRKmpYQ1h9T+JOeCLXt6aztOitSI2tKiRcJwsxc
        KP4gfiFFhUULIaubV/Oa5H3JM5uKrYk0753qoQ3TvNfWGY3Po1WKsS6xA9JepFJK
        7/DWp2c79Q6t4Y23J5UtT/UCgYARsuLZCVrLDU/36uKcYig8l2TdoSgRUkX6zML2
        zt5u67ODa7LPKM16K20z8V75FoMFoUJ8Dyr0b4jfnjhf8YUQn8U/TIWJ1/UxKH1d
        iJckcyiX2KNsZgwpmG7/lTIcJ7PiBSaO7JOJYQiEaIgEy+eS9+jmnsvjd7rEg1dh
        AKcZqQKBgQCE+DdDGubBDvD1FlDyJKa1HivS0EPnAiA249qU3CS7woaMaD59QIru
        anDiIMOQ8mlZx/ZE9yvkFoAhgfXQBfrp+XqlOh1riArDH7ANo8jtVgfa8OkjL/EW
        xReUPzb3rowTtI/4VgeOprchlWUspDoIfIlu4monWnIlx1412aRqPQ==
        -----END RSA PRIVATE KEY-----
    provisioning_key: REDACTED
releases:
- name: shield
  version: 6.4.2
- name: toolbelt
  version: 3.2.10
resource_pools:
- cloud_properties: {}
  name: shield
  network: shield
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 3000-120000
  max_in_flight: 50
  serial: false
  update_watch_time: 3000-120000

