groups:
- jobs:
  - stemcells
  - aws-prod
  - aws-prod-notif
  - aws-staging
  - bosh-lite-alpha
  name: '*'
- jobs:
  - stemcells
  name: upkeep
- jobs:
  - bosh-lite-alpha
  name: α
- jobs:
  - bosh-lite-alpha
  - aws-staging
  name: β
- jobs:
  - bosh-lite-alpha
  - aws-staging
  - aws-prod
  - aws-prod-notif
  name: aws
jobs:
- name: stemcells
  plan:
  - aggregate:
    - get: git
    - get: aws-hvm-stemcell
      params:
        tarball: true
      trigger: true
    - get: warden-stemcell
      params:
        tarball: true
      trigger: true
  - config:
      image_resource:
        source:
          repository: starkandwayne/concourse
        type: docker-image
      inputs:
      - name: git
      - name: aws-hvm-stemcell
        path: stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      - name: warden-stemcell
        path: stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent
      outputs:
      - name: out
      params:
        REPO_OUT: out/git
        STEMCELLS: stemcells
      platform: linux
      run:
        args:
        - ci
        - stemcells
        path: git/bin/genesis
    task: update
  - params:
      rebase: true
      repository: out/git
    put: git
  public: true
  serial: true
- name: aws-prod
  plan:
  - aggregate:
    - get: world-changes
      passed:
      - aws-prod-notif
      resource: aws-β-changes
      trigger: false
    - get: local-changes
      passed:
      - aws-prod-notif
      resource: aws-prod-changes
      trigger: false
  - config:
      image_resource:
        source:
          repository: starkandwayne/concourse
          tag: latest
        type: docker-image
      inputs:
      - name: world-changes
      - name: local-changes
      outputs:
      - name: out
      params:
        CI_BOSHES: |
          aliases:
            target:
              2b8bb4b6-1bca-41f2-8c51-0bb3223c0622: https://10.4.1.80:25555
              39b7432c-3396-4f17-a5cb-d6638108fe4a: https://10.4.1.4:25555
          auth:
            https://10.4.1.4:25555:
              password: REDACTED
              username: admin
            https://10.4.1.80:25555:
              password: REDACTED
              username: admin
        CI_BRANCH: master
        CI_PIPELINE: ""
        CI_PRIVATE_KEY: REDACTED
        CI_SITE_ENV: aws/prod
        CI_VAULT_APP_ID: concourse
        CI_VAULT_USER_ID: shield-pipeline
        CI_WAIT_FOR_CLEAN_BOSH: false
        LOCAL_CHANGES: local-changes
        VAULT_ADDR: https://10.4.1.16:8200
        VAULT_SKIP_VERIFY: 1
        WORKING_DIR: out/git
        WORLD_CHANGES: world-changes
      platform: linux
      run:
        args:
        - ci
        - stage1
        path: world-changes/bin/genesis
    tags: null
    task: aws-prod
  - params:
      rebase: true
      repository: out/git
    put: git
  public: true
  serial: true
- name: aws-staging
  plan:
  - aggregate:
    - get: world-changes
      passed:
      - bosh-lite-alpha
      resource: α-changes
      trigger: true
    - get: local-changes
      resource: aws-changes
      trigger: true
  - config:
      image_resource:
        source:
          repository: starkandwayne/concourse
          tag: latest
        type: docker-image
      inputs:
      - name: world-changes
      - name: local-changes
      outputs:
      - name: out
      params:
        CI_BOSHES: |
          aliases:
            target:
              2b8bb4b6-1bca-41f2-8c51-0bb3223c0622: https://10.4.1.80:25555
              39b7432c-3396-4f17-a5cb-d6638108fe4a: https://10.4.1.4:25555
          auth:
            https://10.4.1.4:25555:
              password: REDACTED
              username: admin
            https://10.4.1.80:25555:
              password: REDACTED
              username: admin
        CI_BRANCH: master
        CI_PIPELINE: ""
        CI_PRIVATE_KEY: REDACTED
        CI_SITE_ENV: aws/staging
        CI_VAULT_APP_ID: concourse
        CI_VAULT_USER_ID: shield-pipeline
        CI_WAIT_FOR_CLEAN_BOSH: false
        LOCAL_CHANGES: local-changes
        VAULT_ADDR: https://10.4.1.16:8200
        VAULT_SKIP_VERIFY: 1
        WORKING_DIR: out/git
        WORLD_CHANGES: world-changes
      platform: linux
      run:
        args:
        - ci
        - stage1
        path: world-changes/bin/genesis
    tags: null
    task: aws-staging
  - params:
      rebase: true
      repository: out/git
    put: aws-β-changes
  public: true
  serial: true
- name: bosh-lite-alpha
  plan:
  - aggregate:
    - get: world-changes
      resource: global-changes
      trigger: true
    - get: local-changes
      resource: bosh-lite-alpha-changes
      trigger: true
  - config:
      image_resource:
        source:
          repository: starkandwayne/concourse
          tag: latest
        type: docker-image
      inputs:
      - name: world-changes
      - name: local-changes
      outputs:
      - name: out
      params:
        CI_BOSHES: |
          aliases:
            target:
              2b8bb4b6-1bca-41f2-8c51-0bb3223c0622: https://10.4.1.80:25555
              39b7432c-3396-4f17-a5cb-d6638108fe4a: https://10.4.1.4:25555
          auth:
            https://10.4.1.4:25555:
              password: REDACTED
              username: admin
            https://10.4.1.80:25555:
              password: REDACTED
              username: admin
        CI_BRANCH: master
        CI_PIPELINE: ""
        CI_PRIVATE_KEY: REDACTED
        CI_SITE_ENV: bosh-lite/alpha
        CI_VAULT_APP_ID: concourse
        CI_VAULT_USER_ID: shield-pipeline
        CI_WAIT_FOR_CLEAN_BOSH: false
        LOCAL_CHANGES: local-changes
        VAULT_ADDR: https://10.4.1.16:8200
        VAULT_SKIP_VERIFY: 1
        WORKING_DIR: out/git
        WORLD_CHANGES: world-changes
      platform: linux
      run:
        args:
        - ci
        - stage1
        path: world-changes/bin/genesis
    tags: null
    task: bosh-lite-alpha
  - params:
      rebase: true
      repository: out/git
    put: α-changes
  public: true
  serial: true
- name: aws-prod-notif
  plan:
  - aggregate:
    - get: world-changes
      passed:
      - aws-staging
      resource: aws-β-changes
      trigger: true
    - get: local-changes
      resource: aws-prod-changes
      trigger: true
  - config:
      image_resource:
        source:
          repository: starkandwayne/concourse
          tag: latest
        type: docker-image
      inputs:
      - name: world-changes
      - name: local-changes
      outputs:
      - name: out
      params:
        CI_SITE_ENV: aws/prod
        DRAFT_FILE: out/notif
        LOCAL_CHANGES: local-changes
        WORLD_CHANGES: world-changes
      platform: linux
      run:
        args:
        - ci
        - draft-message
        path: world-changes/bin/genesis
    tags: null
    task: draft-message
  - params:
      channel: '#name'
      icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
      text_file: out/notif
      username: runwaybot
    put: notification
resource_types:
- name: slack-notification
  source:
    repository: cfcommunity/slack-notification-resource
  type: docker-image
resources:
- name: git
  source:
    branch: master
    private_key: REDACTED
    uri: git@github.com:bodymindarts/shield-deployments
  type: git
- name: aws-prod-changes
  source:
    branch: master
    paths:
    - aws/prod
    - aws/prod/*.yml
    private_key: REDACTED
    uri: git@github.com:bodymindarts/shield-deployments
  type: git
- name: aws-changes
  source:
    branch: master
    paths:
    - aws/site
    - aws/staging
    - aws/staging/*.yml
    private_key: REDACTED
    uri: git@github.com:bodymindarts/shield-deployments
  type: git
- name: aws-β-changes
  source:
    branch: master
    paths:
    - aws/staging/.site
    - aws/staging/.global
    private_key: REDACTED
    uri: git@github.com:bodymindarts/shield-deployments
  type: git
- name: global-changes
  source:
    branch: master
    paths:
    - bin/genesis
    - global
    private_key: REDACTED
    uri: git@github.com:bodymindarts/shield-deployments
  type: git
- name: bosh-lite-alpha-changes
  source:
    branch: master
    paths:
    - bosh-lite/site
    - bosh-lite/alpha
    - bosh-lite/alpha/*.yml
    private_key: REDACTED
    uri: git@github.com:bodymindarts/shield-deployments
  type: git
- name: α-changes
  source:
    branch: master
    paths:
    - bosh-lite/alpha/.global
    private_key: REDACTED
    uri: git@github.com:bodymindarts/shield-deployments
  type: git
- name: notification
  source:
    url: https://slack/web/hook/url
  type: slack-notification
- name: aws-hvm-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  type: bosh-io-stemcell
- name: warden-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
  type: bosh-io-stemcell

